name: AsyncMcRemoteWorldGenClient
main: org.asyncmc.worldgen.remote.client.powernukkit.AsyncMcWorldGenPowerNukkitClientPlugin
version: "@version@"
api: ["1.0.13"]
depend:
  - PowerNukkit
  - KotlinLib
softdepend:
  - MobPlugin
author: "joserobjr <joserobjr@powernukkit.org>"
load: STARTUP
